#pragma once

static const char* guimsg2str(GUIMSG msg)
{
    switch(msg)
    {
    case GUI_DISASSEMBLE_AT: return "GUI_DISASSEMBLE_AT";
    case GUI_SET_DEBUG_STATE: return "GUI_SET_DEBUG_STATE";
    case GUI_ADD_MSG_TO_LOG: return "GUI_ADD_MSG_TO_LOG";
    case GUI_CLEAR_LOG: return "GUI_CLEAR_LOG";
    case GUI_UPDATE_REGISTER_VIEW: return "GUI_UPDATE_REGISTER_VIEW";
    case GUI_UPDATE_DISASSEMBLY_VIEW: return "GUI_UPDATE_DISASSEMBLY_VIEW";
    case GUI_UPDATE_BREAKPOINTS_VIEW: return "GUI_UPDATE_BREAKPOINTS_VIEW";
    case GUI_UPDATE_WINDOW_TITLE: return "GUI_UPDATE_WINDOW_TITLE";
    case GUI_GET_WINDOW_HANDLE: return "GUI_GET_WINDOW_HANDLE";
    case GUI_DUMP_AT: return "GUI_DUMP_AT";
    case GUI_SCRIPT_ADD: return "GUI_SCRIPT_ADD";
    case GUI_SCRIPT_CLEAR: return "GUI_SCRIPT_CLEAR";
    case GUI_SCRIPT_SETIP: return "GUI_SCRIPT_SETIP";
    case GUI_SCRIPT_ERROR: return "GUI_SCRIPT_ERROR";
    case GUI_SCRIPT_SETTITLE: return "GUI_SCRIPT_SETTITLE";
    case GUI_SCRIPT_SETINFOLINE: return "GUI_SCRIPT_SETINFOLINE";
    case GUI_SCRIPT_MESSAGE: return "GUI_SCRIPT_MESSAGE";
    case GUI_SCRIPT_MSGYN: return "GUI_SCRIPT_MSGYN";
    case GUI_SYMBOL_LOG_ADD: return "GUI_SYMBOL_LOG_ADD";
    case GUI_SYMBOL_LOG_CLEAR: return "GUI_SYMBOL_LOG_CLEAR";
    case GUI_SYMBOL_SET_PROGRESS: return "GUI_SYMBOL_SET_PROGRESS";
    case GUI_SYMBOL_UPDATE_MODULE_LIST: return "GUI_SYMBOL_UPDATE_MODULE_LIST";
    case GUI_REF_ADDCOLUMN: return "GUI_REF_ADDCOLUMN";
    case GUI_REF_SETROWCOUNT: return "GUI_REF_SETROWCOUNT";
    case GUI_REF_GETROWCOUNT: return "GUI_REF_GETROWCOUNT";
    case GUI_REF_DELETEALLCOLUMNS: return "GUI_REF_DELETEALLCOLUMNS";
    case GUI_REF_SETCELLCONTENT: return "GUI_REF_SETCELLCONTENT";
    case GUI_REF_GETCELLCONTENT: return "GUI_REF_GETCELLCONTENT";
    case GUI_REF_RELOADDATA: return "GUI_REF_RELOADDATA";
    case GUI_REF_SETSINGLESELECTION: return "GUI_REF_SETSINGLESELECTION";
    case GUI_REF_SETPROGRESS: return "GUI_REF_SETPROGRESS";
    case GUI_REF_SETCURRENTTASKPROGRESS: return "GUI_REF_SETCURRENTTASKPROGRESS";
    case GUI_REF_SETSEARCHSTARTCOL: return "GUI_REF_SETSEARCHSTARTCOL";
    case GUI_STACK_DUMP_AT: return "GUI_STACK_DUMP_AT";
    case GUI_UPDATE_DUMP_VIEW: return "GUI_UPDATE_DUMP_VIEW";
    case GUI_UPDATE_THREAD_VIEW: return "GUI_UPDATE_THREAD_VIEW";
    case GUI_ADD_RECENT_FILE: return "GUI_ADD_RECENT_FILE";
    case GUI_SET_LAST_EXCEPTION: return "GUI_SET_LAST_EXCEPTION";
    case GUI_GET_DISASSEMBLY: return "GUI_GET_DISASSEMBLY";
    case GUI_MENU_ADD: return "GUI_MENU_ADD";
    case GUI_MENU_ADD_ENTRY: return "GUI_MENU_ADD_ENTRY";
    case GUI_MENU_ADD_SEPARATOR: return "GUI_MENU_ADD_SEPARATOR";
    case GUI_MENU_CLEAR: return "GUI_MENU_CLEAR";
    case GUI_SELECTION_GET: return "GUI_SELECTION_GET";
    case GUI_SELECTION_SET: return "GUI_SELECTION_SET";
    case GUI_GETLINE_WINDOW: return "GUI_GETLINE_WINDOW";
    case GUI_AUTOCOMPLETE_ADDCMD: return "GUI_AUTOCOMPLETE_ADDCMD";
    case GUI_AUTOCOMPLETE_DELCMD: return "GUI_AUTOCOMPLETE_DELCMD";
    case GUI_AUTOCOMPLETE_CLEARALL: return "GUI_AUTOCOMPLETE_CLEARALL";
    case GUI_SCRIPT_ENABLEHIGHLIGHTING: return "GUI_SCRIPT_ENABLEHIGHLIGHTING";
    case GUI_ADD_MSG_TO_STATUSBAR: return "GUI_ADD_MSG_TO_STATUSBAR";
    case GUI_UPDATE_SIDEBAR: return "GUI_UPDATE_SIDEBAR";
    case GUI_REPAINT_TABLE_VIEW: return "GUI_REPAINT_TABLE_VIEW";
    case GUI_UPDATE_PATCHES: return "GUI_UPDATE_PATCHES";
    case GUI_UPDATE_CALLSTACK: return "GUI_UPDATE_CALLSTACK";
    case GUI_UPDATE_SEHCHAIN: return "GUI_UPDATE_SEHCHAIN";
    case GUI_SYMBOL_REFRESH_CURRENT: return "GUI_SYMBOL_REFRESH_CURRENT";
    case GUI_UPDATE_MEMORY_VIEW: return "GUI_UPDATE_MEMORY_VIEW";
    case GUI_REF_INITIALIZE: return "GUI_REF_INITIALIZE";
    case GUI_LOAD_SOURCE_FILE: return "GUI_LOAD_SOURCE_FILE";
    case GUI_MENU_SET_ICON: return "GUI_MENU_SET_ICON";
    case GUI_MENU_SET_ENTRY_ICON: return "GUI_MENU_SET_ENTRY_ICON";
    case GUI_SHOW_CPU: return "GUI_SHOW_CPU";
    case GUI_ADD_QWIDGET_TAB: return "GUI_ADD_QWIDGET_TAB";
    case GUI_SHOW_QWIDGET_TAB: return "GUI_SHOW_QWIDGET_TAB";
    case GUI_CLOSE_QWIDGET_TAB: return "GUI_CLOSE_QWIDGET_TAB";
    case GUI_EXECUTE_ON_GUI_THREAD: return "GUI_EXECUTE_ON_GUI_THREAD";
    case GUI_UPDATE_TIME_WASTED_COUNTER: return "GUI_UPDATE_TIME_WASTED_COUNTER";
    case GUI_SET_GLOBAL_NOTES: return "GUI_SET_GLOBAL_NOTES";
    case GUI_GET_GLOBAL_NOTES: return "GUI_GET_GLOBAL_NOTES";
    case GUI_SET_DEBUGGEE_NOTES: return "GUI_SET_DEBUGGEE_NOTES";
    case GUI_GET_DEBUGGEE_NOTES: return "GUI_GET_DEBUGGEE_NOTES";
    case GUI_DUMP_AT_N: return "GUI_DUMP_AT_N";
    case GUI_DISPLAY_WARNING: return "GUI_DISPLAY_WARNING";
    case GUI_REGISTER_SCRIPT_LANG: return "GUI_REGISTER_SCRIPT_LANG";
    case GUI_UNREGISTER_SCRIPT_LANG: return "GUI_UNREGISTER_SCRIPT_LANG";
    case GUI_UPDATE_ARGUMENT_VIEW: return "GUI_UPDATE_ARGUMENT_VIEW";
    case GUI_FOCUS_VIEW: return "GUI_FOCUS_VIEW";
    case GUI_UPDATE_WATCH_VIEW: return "GUI_UPDATE_WATCH_VIEW";
    case GUI_LOAD_GRAPH: return "GUI_LOAD_GRAPH";
    case GUI_GRAPH_AT: return "GUI_GRAPH_AT";
    case GUI_UPDATE_GRAPH_VIEW: return "GUI_UPDATE_GRAPH_VIEW";
    case GUI_SET_LOG_ENABLED: return "GUI_SET_LOG_ENABLED";
    case GUI_ADD_FAVOURITE_TOOL: return "GUI_ADD_FAVOURITE_TOOL";
    case GUI_ADD_FAVOURITE_COMMAND: return "GUI_ADD_FAVOURITE_COMMAND";
    case GUI_SET_FAVOURITE_TOOL_SHORTCUT: return "GUI_SET_FAVOURITE_TOOL_SHORTCUT";
    case GUI_FOLD_DISASSEMBLY: return "GUI_FOLD_DISASSEMBLY";
    case GUI_SELECT_IN_MEMORY_MAP: return "GUI_SELECT_IN_MEMORY_MAP";
    case GUI_GET_ACTIVE_VIEW: return "GUI_GET_ACTIVE_VIEW";
    case GUI_MENU_SET_ENTRY_CHECKED: return "GUI_MENU_SET_ENTRY_CHECKED";
    case GUI_ADD_INFO_LINE: return "GUI_ADD_INFO_LINE";
    case GUI_PROCESS_EVENTS: return "GUI_PROCESS_EVENTS";
    case GUI_TYPE_ADDNODE: return "GUI_TYPE_ADDNODE";
    case GUI_TYPE_CLEAR: return "GUI_TYPE_CLEAR";
    case GUI_UPDATE_TYPE_WIDGET: return "GUI_UPDATE_TYPE_WIDGET";
    case GUI_CLOSE_APPLICATION: return "GUI_CLOSE_APPLICATION";
    case GUI_MENU_SET_VISIBLE: return "GUI_MENU_SET_VISIBLE";
    case GUI_MENU_SET_ENTRY_VISIBLE: return "GUI_MENU_SET_ENTRY_VISIBLE";
    case GUI_MENU_SET_NAME: return "GUI_MENU_SET_NAME";
    case GUI_MENU_SET_ENTRY_NAME: return "GUI_MENU_SET_ENTRY_NAME";
    case GUI_FLUSH_LOG: return "GUI_FLUSH_LOG";
    case GUI_MENU_SET_ENTRY_HOTKEY: return "GUI_MENU_SET_ENTRY_HOTKEY";
    case GUI_REF_SEARCH_GETROWCOUNT: return "GUI_REF_SEARCH_GETROWCOUNT";
    case GUI_REF_SEARCH_GETCELLCONTENT: return "GUI_REF_SEARCH_GETCELLCONTENT";
    case GUI_MENU_REMOVE: return "GUI_MENU_REMOVE";
    case GUI_REF_ADDCOMMAND: return "GUI_REF_ADDCOMMAND";
    case GUI_OPEN_TRACE_FILE: return "GUI_OPEN_TRACE_FILE";
    case GUI_UPDATE_TRACE_BROWSER: return "GUI_UPDATE_TRACE_BROWSER";
    case GUI_INVALIDATE_SYMBOL_SOURCE: return "GUI_INVALIDATE_SYMBOL_SOURCE";
    }
    return "<unknown>";
}

static const char* dbgstate2str(DBGSTATE s)
{
    switch(s)
    {
    case initialized: return "initialized";
    case paused: return "paused";
    case running: return "running";
    case stopped: return "stopped";
    }
    return "<unknown>";
}